services:

  caspnetti_nginx_development:
    container_name: caspnetti_nginx_development
    build:
      context: ./
      dockerfile: docker/development/nginx/Dockerfile
    depends_on:
      - caspnetti_aspnet_development
    image: caspnetti_nginx_development
    ports:
      - 443:443
    volumes:
      - ./docker/development/nginx/logs:/var/log/nginx
    networks:
      - caspnetti_development

  caspnetti_aspnet_development:
    build:
      context: ./
      dockerfile: ./docker/development/aspnet/Dockerfile
    container_name: caspnetti_aspnet_development
    depends_on:
      - caspnetti_mssql_development
    env_file:
      - ./docker/development/aspnet/.env.local
    image: caspnetti_aspnet_development
    volumes:
      - ./src/backend:/caspnetti
    networks:
      - caspnetti_development

  caspnetti_mssql_development:
    build:
      context: ./
      dockerfile: ./docker/development/mssql/Dockerfile
    container_name: caspnetti_mssql_development
    env_file:
      - ./docker/development/mssql/.env.local
    image: caspnetti_mssql_development
    volumes:
      - ./docker/development/mssql/data:/var/opt/mssql/data
    networks:
      - caspnetti_development

  caspnetti_adminer_development:
    build:
      context: ./
      dockerfile: ./docker/development/adminer/Dockerfile
    container_name: caspnetti_adminer_development
    depends_on:
      - caspnetti_mssql_development
    env_file:
      - ./docker/development/adminer/.env.local
    image: caspnetti_adminer_development
    ports:
      - 8000:8080
    networks:
      - caspnetti_development

  caspnetti_vue_development:
    build:
      context: ./
      dockerfile: ./docker/development/vue/Dockerfile
    container_name: caspnetti_vue_development
    depends_on:
      - caspnetti_aspnet_development
    env_file:
      - ./docker/development/vue/.env.local
    image: caspnetti_vue_development
    ports:
      - 80:80
    volumes:
      - ./src/frontend:/caspnetti
    networks:
      - caspnetti_development

networks:

  caspnetti_development:
    name: caspnetti_development
    driver: bridge
