services:

  caspnetti_nginx_production:
    container_name: caspnetti_nginx_production
    build:
      context: ./
      dockerfile: docker/production/nginx/Dockerfile
    depends_on:
      - caspnetti_aspnet_production
    image: caspnetti_nginx_production
    ports:
      - 443:443
    volumes:
      - ./docker/production/nginx/logs:/var/log/nginx
    networks:
      - reproxy
      - caspnetti_production

  caspnetti_aspnet_production:
    build:
      context: ./
      dockerfile: ./docker/production/aspnet/Dockerfile
    container_name: caspnetti_aspnet_production
    depends_on:
      - caspnetti_mssql_production
    env_file:
      - ./docker/production/aspnet/.env.local
    image: caspnetti_aspnet_production
    networks:
      - caspnetti_production

  caspnetti_mssql_production:
    build:
      context: ./
      dockerfile: ./docker/production/mssql/Dockerfile
    container_name: caspnetti_mssql_production
    env_file:
      - ./docker/production/mssql/.env.local
    image: caspnetti_mssql_production
    volumes:
      - ./docker/production/mssql/data:/var/opt/mssql/data
    networks:
      - caspnetti_production

  caspnetti_vue_production:
    build:
      context: ./
      dockerfile: ./docker/production/vue/Dockerfile
    container_name: caspnetti_vue_production
    depends_on:
      - caspnetti_aspnet_production
    env_file:
      - ./docker/production/vue/.env.local
    image: caspnetti_vue_production
    ports:
      - 80:80
    networks:
      - caspnetti_production

networks:

  caspnetti_production:
    name: caspnetti_production
    driver: bridge

  reproxy:
    external: true
    name: reproxy
